### ISSUE TITLE
Prestige talents invalid function Clamp

### ISSUE THREAD

**Issue by seutje** [andrew6180/Ascension_Weakauras#11]
Hey,

The prestige talents WeakAura wasn't working for me until I changed
`local count = Clamp(rank - curR, 0, maxR)`
to
`local count = math.clamp(rank - curR, 0, maxR)`
on line 49 of the actions code.

**Comment by andrew6180** [comment]
Hero Architect is now available for automatic talents on seasonal.

**Comment by seutje** [comment]
Have you tried it? It doesn't work for me, can't actually activate any builds while leveling...

**Comment by andrew6180** [comment]
> Have you tried it? It doesn't work for me, can't actually activate any builds while leveling...

make sure you've updated / repaired from launcher. It is indeed working.
